#!/bin/sh
#SBATCH --account=cm30225
#SBATCH --partition=teaching

#SBATCH --job-name=ac2288_mpi

#SBATCH --nodes=2


#SBATCH --ntasks-per-node=4
#SBATCH --time=00:15:00

#SBATCH --output=myjob.out

#SBATCH --mail-user=ac2288@bath.ac.uk

#module load slurm

module load intel/compiler
module load openmpi/intel

make

echo "$SLURM_NTASKS"

#mpirun -np $SLURM_NTASKS ./main -d 100 -p 10E-4 array3

mpirun -np 2 ./main -d 1000 -p 10E-4 array3
mpirun -np 4 ./main -d 1000 -p 10E-4 array3
mpirun -np 5 ./main -d 1000 -p 10E-4 array3
mpirun -np 6 ./main -d 1000 -p 10E-4 array3
mpirun -np 7 ./main -d 1000 -p 10E-4 array3
mpirun -np 8 ./main -d 1000 -p 10E-4 array3
mpirun -np 9 ./main -d 1000 -p 10E-4 array3
mpirun -np 10 ./main -d 1000 -p 10E-4 array3
mpirun -np 11 ./main -d 1000 -p 10E-4 array3
mpirun -np 12 ./main -d 1000 -p 10E-4 array3
mpirun -np 16 ./main -d 1000 -p 10E-4 array3
mpirun -np 24 ./main -d 1000 -p 10E-4 array3
mpirun -np 32 ./main -d 1000 -p 10E-4 array3
