#!/bin/sh
#SBATCH --account=cm30225
#SBATCH --partition=teaching

#SBATCH --job-name=ac2288_mpi

#SBATCH --nodes=2


#SBATCH --ntasks-per-node=8
#SBATCH --time=00:15:00

#SBATCH --output=myjob.out


module load intel/compiler
module load openmpi/intel

mpirun -np $SLURM_NTASKS ./main -d 100 -p 10E-4 array3
