#!/bin/sh
#SBATCH --account=cm30225
#SBATCH --partition=teaching

#SBATCH --job-name=ac2288_mpi

#SBATCH --nodes=2


#SBATCH --ntasks-per-node=16
#SBATCH --time=00:15:00

#SBATCH --output=myjob.out


. /etc/profile.d/modules.sh
module purge
module load slurm
module load intel/compiler
module load openmpi/intel

make

#mpirun -np 2 xterm -e gdb --args ./main -d 10 -p 10E-10 array1
#mpirun -np 8 ./main -d 20 -p 10E-10 array2
#mpirun -np $SLURM_NTASKS ./test -d 100 -p 10E-10 array1

mpirun -np $SLURM_NTASKS ./main -d 1000 -p 10E-6 array4
